### PR TITLE
[bugfix] fixed bug with options = this.props.options

### PR DESCRIPTION
**Pull request by Boorj**
There was a mistake. See the commit

### CODE REVIEW

**Comment by rkit** [comment]
This is not mistake. `options` in props.
Are you sure about that?

**Comment by Boorj** [comment]
Yes, but in _current_ version, it's `{ options } = this.props;` and not the way i wrote in subj :smile: .
On the next line there's a comparsion
```js
if (!shallowEqualFuzzy(prevProps.options, options))
```
Seems that options has to take data from `this.props.options`, not `this.props`. And, actually, that bugfix made my app work properly.

**Comment by rkit** [comment]
```js
const { options } = this.props.options;
```
This code will be return `undefined` ([see](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment))
You can check it.

**Comment by Boorj** [comment]
Got that, destructive assignment, yeah.. Sorry, i was using port for coffeescript (see [here](https://gist.github.com/Boorj/871da9f6d33d31436f14ad4c12a7e042)). And lost that, during conversion. Using `u.deobj` function for destructive assignment (for old JS).

**Pull request closed without merging**
