### PR TITLE
Added option "selected" to items

### PR DESCRIPTION
**Pull request by igogo5yo**

### CODE REVIEW

**Comment by rkit** [comment]
I released a new version (0.1.0), now you can set a default value, as follows:
https://github.com/rkit/react-select2-wrapper#with-default-value
https://github.com/rkit/react-select2-wrapper#with-default-multiple-value

**Comment by igogo5yo** [comment]
Thanx!

**Comment by CWSites** [comment]
Hey @rkit the links you provided no longer work, where can I find out more about using "selected"?

**Comment by rkit** [comment]
@CWSites 

```
{ text: 'Tag 1', id: 1, selected: true },
```

**Pull request closed without merging**
