### PR TITLE
Jquery version upgrade

### PR DESCRIPTION
**Pull request by dopeddude**
Fix for the issue, 

https://github.com/rkit/react-select2-wrapper/issues/36

### CODE REVIEW

**Comment by rkit** [comment]
Please try delete `jquery` from dependencies of this component (react-select2-wrapper) 
and add `jquery` to your package.json. If it helps, I will delete `jquery` dependency.

**Comment by dopeddude** [comment]
in that case will you like to add jquery to peer deps in the following format:

"jquery": "*"

**Comment by rkit** [comment]
I agree.

**Comment by rkit** [comment]
Thanks!

**Comment by dopeddude** [comment]
@rkit , Thanks for the merge and publish over npm.

**Pull request merged**
